version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=Atscale-ELK-Cluster
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elk-node-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    depends_on:
      - elasticsearch
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic
   
  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.0
    depends_on:
      - elasticsearch
      - kibana
    container_name: logstash
    volumes:
      - logstash-data:/usr/share/logstash
    networks:
      - elastic
      
volumes:
  elk-node-data:
    driver: local
  logstash-data:
    driver: local
    
networks:
  elastic:
    driver: bridge